# Generated by Django 5.0.4 on 2024-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_veterinarian_zookeeper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinarian',
            old_name='licens_number',
            new_name='license_number',
        ),
        migrations.AlterField(
            model_name='zookeeper',
            name='specialty',
            field=models.CharField(choices=[('Mammals', 'Mammals'), ('Birds', 'Birds'), ('Reptiles', 'Reptiles'), ('others', 'others')], max_length=10),
        ),
    ]
