# Generated by Django 5.0.4 on 2024-06-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
